name: "publish"
on:
  push:
    branches:
      - main

jobs:
  publish-tauri:
    permissions:
      pull-requests: write
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: install frontend dependencies
        run: pnpm install
      - uses: tauri-apps/tauri-action@v0
        id: tauri-action
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: "bundol v__VERSION__"
          prerelease: false
          includeUpdaterJson: true
          updaterJsonPreferNsis: true
      - name: debug-print
        run: |
          echo "tauri-action outputs:"
          echo "  ${{ steps.tauri-action.outputs.releaseId }}"
          echo "  ${{ steps.tauri-action.outputs.releaseHtmlUrl }}"
          echo "  ${{ steps.tauri-action.outputs.releaseUploadUrl }}"
          echo "  ${{ steps.tauri-action.outputs.artifactPaths }}"
      - name: Create Updater JSON
        run: |
          echo pwd
          echo ls -la 
          export signature=$(cat src-tauri/target/release/bundle/nsis/bundol_${{ steps.tauri-action.outputs.releaseId }}_x64-setup.nsis.zip.sig)
          echo "{
            "version": "${{ steps.tauri-action.outputs.releaseId }}",
            "platforms": {
                "windows-x86_64": {
                    "signature": "${signature}",
                    "url": "https://gist.github.com/eurmn/0fa827e6892a79ae305921ae947f8764"
                }
            }
          }" > build/updater.json
      - name: GIST Updater
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          gist_id: from_gist_url
          file_path: build/book.pdf
          file_type: binary
