name: "publish"
on:
  push:
    branches:
      - main

jobs:
  publish-tauri:
    permissions:
      pull-requests: write
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: install frontend dependencies
        run: pnpm install
      - uses: tauri-apps/tauri-action@v0
        id: tauri-action
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: __VERSION__
          releaseName: "bundol v__VERSION__"
          prerelease: false
          includeUpdaterJson: true
          updaterJsonPreferNsis: true
      - name: Updater JSON Generator
        run: |
          echo "{
            \"version\": \"${{ steps.tauri-action.outputs.releaseId }}\",
            \"pub_date\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\",
            \"platforms\": {
              \"windows-x86_64\": {
                \"signature\": \"$(cat src-tauri/target/release/bundle/nsis/bundol_${{ steps.tauri-action.outputs.releaseId }}_x64-setup.nsis.zip.sig)\",
                \"url\": \"https://github.com/eurmn/bundol/releases/download/${{ steps.tauri-action.outputs.releaseId }}/bundol_${{ steps.tauri-action.outputs.releaseId }}_x64-setup.nsis.zip\"
              }
            }
          }" > latest.json
      - name: GIST Updater
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: 0fa827e6892a79ae305921ae947f8764
          file_path: latest.json
          file_type: json
