name: "publish"
on:
  push:
    branches:
      - main

jobs:
  publish-tauri:
    permissions:
      pull-requests: write
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: install frontend dependencies
        run: pnpm install
      - uses: tauri-apps/tauri-action@v0
        id: tauri-action
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: __VERSION__
          releaseName: "bundol v__VERSION__"
          prerelease: false
      - name: Updater JSON Generator
        shell: python
        run: |
          import json
          from datetime import datetime

          with open('src-tauri/tauri.conf.json', 'r') as f:
            data = json.load(f)
          version = data['package']['version']

          with open(f'src-tauri/target/release/bundle/nsis/bundol_{version}_x64-setup.nsis.zip.sig') as f:
            signature = f.read()

          date = datetime.now().isoformat()

          with open('latest.json', 'w') as f:
            json.dump({
              "version": version,
              "pub_date": f"{date}Z",
              "platforms": {
                "windows-x86_64": {
                  "signature": signature,
                  "url": f"https://github.com/eurmn/bundol/releases/download/{version}/bundol_{version}_x64-setup.nsis.zip"
                }
              }
            }, f
          )
      - name: GIST Updater
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: 0fa827e6892a79ae305921ae947f8764
          file_path: latest.json
          file_type: json
