name: "publish"
on:
  push:
    branches:
      - main

jobs:
  publish-tauri:
    outputs:
      release_id: ${{ steps.tauri-action.outputs.releaseId }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: install frontend dependencies
        run: pnpm install
      - uses: tauri-apps/tauri-action@v0
        id: tauri-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: "bundol v__VERSION__"
          prerelease: false
          includeUpdaterJson: true
          updaterJsonPreferNsis: true
      - name: debug-print
        run: echo TAURI-RELEASE "${{ steps.tauri-action.outputs.releaseId }}""
