name: "testing"
on:
  push:
    branches:
      - main

jobs:
  publish-tauri:
    permissions:
      pull-requests: write
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Create Updater JSON
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
        shell: bash
        run: |
          pwd
          ls -la
          echo "test" > test.txt
      - name: GIST Updater
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          gist_id: 0fa827e6892a79ae305921ae947f8764
          file_path: test.txt
          file_type: txt
